import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";
import { AuthStatus } from "../types/custom-next-auth";
import { Spinner } from "../components/spinner/spinner";

const Home: NextPage = (props) => {
  const { data: session, status } = useSession();

  console.log("session", session);
  console.log("status", status);

  if (status === AuthStatus.LOADING) {
    return <Spinner />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          <h1>{session?.user?.name}</h1>
          <p>
            Signed in as {session?.user?.email} <br />
          </p>
          <button className="btn" onClick={() => signOut()}>
            Sign out
          </button>
          {session?.user?.image ? (
            <Image
              className="rounded-full"
              src={session?.user?.image}
              width={50}
              height={50}
              alt="User image"
            />
          ) : null}
        </>
      ) : (
        <>
          Not signed in <br />
          <button className="btn" onClick={() => signIn()}>
            Sign in
          </button>
        </>
      )}

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4"></main>
    </>
  );
};

export default Home;
